Ce bout de code doit être executé après : 

avoir effectué un repeatmasker

avoir effectuer le code repeatmasker_to bedtools

être passé sur R pour ne garder que les meilleurs hits de bedtools avec le code display_bedtools.

Il permet de mettre les sequence d'interet au bon format pour aller les pecher avec bedtools getfasta.

In [1]:
import pandas as pa
import numpy as np
import itertools
import csv

In [2]:
res_bedtools = pa.read_csv("/home/tkastylevsky/results/bedtools_analysis/chk_galgal6_chr1_repeat_fam_intersect_besthit_data.csv")
data = pa.read_csv('/home/tkastylevsky/FASTA_files/gallus_gallus_proper/gallus_proper_chr1/chr1.fa.out_1.gff',header = None, sep = '\t')
data.columns = ['query_seq','source','feature','pos_query_begin','pos_query_end', 'perc_div', 'strand','phase', 'A_ID']

In [13]:
DNA_data = res_bedtools[(res_bedtools['repeat_class_A'] != res_bedtools['repeat_class_B'])&(res_bedtools['repeat_class_A'] == 'DNA')]
DNA_data_1 = DNA_data
DNA_data = DNA_data[['A_ID']]
DNA_data = pa.merge(DNA_data, data, on = 'A_ID', how = 'inner')
DNA_data = DNA_data[['query_seq','source','feature','pos_query_begin','pos_query_end', 'perc_div', 'strand','phase', 'A_ID']]

In [14]:
DNA_data_1 = pa.merge(DNA_data_1, data[['pos_query_begin','pos_query_end','A_ID']], on = 'A_ID', how = 'inner')
DNA_data_1

,A_ID,B_ID,intersect_A,intersect_B,matching_repeat_A,repeat_class_A,repeat_family_A,TE_A_ID,matching_repeat_B,repeat_class_B,repeat_family_B,TE_B_ID,pos_query_begin,pos_query_end
0,278,200,0.581140,0.992509,rnd-2_family-104,DNA,TcMar-Mariner,253,GGERV10_LTR,LTR,ERVL,162,271331,271787
1,393,286,0.383721,1.000000,DF0002877,DNA,CMC-EnSpm,360,GGERVL-C-int,LTR,ERVL,233,358644,358730
2,396,290,1.000000,1.000000,rnd-3_family-456,DNA,TcMar-Mariner,363,GGERV20_I-int,LTR,ERVL,236,360700,360940
3,413,303,1.000000,1.000000,rnd-1_family-54,DNA,TcMar-Mariner,378,CR1-C,LINE,CR1,246,366492,366559
4,527,402,0.704082,1.000000,DF0003162,DNA,MULE-MuDR,486,CR1-Y4,LINE,CR1,331,462305,462403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6900,162998,142484,1.000000,1.000000,rnd-1_family-49,DNA,TcMar-Mariner,158267,(GTTGT)n,Simple_repeat,NaN,135465,197235021,197235078
6901,163015,142492,1.000000,1.000000,rnd-1_family-49,DNA,TcMar-Mariner,158282,(A)n,Simple_repeat,NaN,135473,197245929,197245986
6902,163049,142514,0.870000,0.358025,DF0003731,DNA,hAT-Ac,158312,CR1-X2,LINE,CR1,135494,197270986,197271086
6903,163051,142514,1.000000,0.176955,DF0003731,DNA,hAT-Ac,158312,CR1-X2,LINE,CR1,135494,197271189,197271232
6904,163370,142786,0.486486,1.000000,DF0003386,DNA,CMC-EnSpm,158614,CR1-D2,LINE,CR1,135757,197549069,197549143

In [ ]:
DNA_data.to_csv("/home/tkastylevsky/results/bedtools_analysis/chk_galgal6_chr1_DNATE_intersect_type_unmatch.csv", sep = '\t', header = False, index = False)